address:
  1: Quận 1
  2: Quận 2
  3: Quận 3
  4: Quận 4
  5: Quận 5
  6: Quận 6
  7: Quận 7
  8: Quận 8
  9: Quận 9
  10: Quận 10
  11: Quận 11
  12: Quận Bình Tân
  13: Quận Bình Thạnh
  14: Quận Gò Vấp
  15: Quận Phú Nhuận
  16: Quận Tân Bình
  17: Quận Tân Phú
  18: Quận Thủ Đức
  19: Huyện Bình Chánh
  19: Huyện Cần Giờ
  19: Huyện Củ Chi
  19: Huyện Hóc Môn
  19: Huyện Nhà Bè

time: 
  0: 7h - 9h
  1: 9h - 11h
  2: 13h - 15h
  3: 15h - 17h
  4: 17h - 19h
  5: 19h - 21h

degree:
  0: degree_not_known
  1: student
  2: college
  3: university
  4: master

sex:
  1: sex_not_known 
  2: man
  3: woman
